# credit: https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "py36-x64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "py37-x64"

install:
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
<<<<<<< HEAD
  - "%PYTHON%\\python.exe -m flake8 slack"
  - "%PYTHON%\\python.exe -m pytest --cov-report= --cov=slack tests"
=======
  - "%PYTHON%\\python.exe setup.py validate"
>>>>>>> 415389d64f38ab19e776b94514d5c9f6eae1fdcc

on_success:
  - "%PYTHON%\\python.exe -m codecov -e win-%PYTHON_VERSION%"